# This rule is not used by the project opg-ewbi itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the opg.ewbi.nby.one.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: opg-ewbi
    app.kubernetes.io/managed-by: kustomize
  name: applicationinstance-editor-role
rules:
- apiGroups:
  - opg.ewbi.nby.one
  resources:
  - applicationinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opg.ewbi.nby.one
  resources:
  - applicationinstances/status
  verbs:
  - get
