# This rule is not used by the project opg-ewbi itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over opg.ewbi.nby.one.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: opg-ewbi
    app.kubernetes.io/managed-by: kustomize
  name: artefact-admin-role
rules:
- apiGroups:
  - opg.ewbi.nby.one
  resources:
  - artefacts
  verbs:
  - '*'
- apiGroups:
  - opg.ewbi.nby.one
  resources:
  - artefacts/status
  verbs:
  - get
