apiVersion: opg.ewbi.nby.one/v1beta1
kind: Application
metadata:
  namespace: federation-guest
  labels:
    opg.ewbi.nby.one/federation-context-id: 4d559f1b-f008-58c2-a2f8-0596892a0f7a # get this from Guest Federation's status
    opg.ewbi.nby.one/federation-relation: "guest"
    opg.ewbi.nby.one/id: "app-2dae064c-28cc-456e-8b0a-dd67bab7d8f7"
  name: "app-2dae064c-28cc-456e-8b0a-dd67bab7d8f7"
spec:
  appMetaData:
    accessToken: a1234567890123456789012345678901234567890123456789012345678901
    name: my-test-app
    version: "37.6"
  appProviderId: nearbycomputing
  componentSpecs:
    - artefactId: "artefact-2dae064c-28cc-456e-8b0a-dd67bab7d8f7"
  qoSProfile:
    latencyConstraints: LOW
    multiUserClients: APP_TYPE_SINGLE_USER
    provisioning: true
    usersPerAppInst: 1
  statusLink: https://onboard.app/callback
