apiVersion: opg.ewbi.nby.one/v1beta1
kind: ApplicationInstance
metadata:
  namespace: federation-guest
  labels:
    opg.ewbi.nby.one/federation-context-id: 4d559f1b-f008-58c2-a2f8-0596892a0f7a # get this from Guest Federation's status
    opg.ewbi.nby.one/federation-relation: "guest"
    opg.ewbi.nby.one/id: "app-inst-2dae064c-28cc-456e-8b0a-dd67bab7d8f7"
  name: "app-inst-2dae064c-28cc-456e-8b0a-dd67bab7d8f7"
spec:
  appId: "app-2dae064c-28cc-456e-8b0a-dd67bab7d8f7"
  appProviderId: nearbycomputing
  appVersion: 1.23.3
  zoneInfo:
    flavourId: NOT_SPECIFIED
    resPool: mock-res-pool
    resourceConsumption: RESERVED_RES_AVOID
    zoneId: "zone-es-madrid-001"
