# Create this when the Origin Partner (Client)
# credentials are created in the host system
apiVersion: opg.ewbi.nby.one/v1beta1
kind: Federation
metadata:
  namespace: federation-host
  annotations:
    opg.ewbi.nby.one/origin-mcc: "001"
    opg.ewbi.nby.one/origin-mncs: "001"
  labels:
    opg.ewbi.nby.one/federation-relation: host
    opg.ewbi.nby.one/origin-operator-name: guestName
    opg.ewbi.nby.one/origin-client-id: 3acde22c-d245-480d-b01e-24e38e01806d
    opg.ewbi.nby.one/origin-country-code: ES
  name: fed-e35f69d8-ae5a-456b-9f95-d950e4c03e8d
spec:
  offeredAvailabilityZones:
    - zoneId: "2a8fffaf-50de-4f93-8c6f-05f1c84b5a5f"
      geolocation: "40.4168,-3.7038"
      geographyDetails: "Madrid, Spain - Urban edge location"
  guestPartnerCredentials:
    clientId: 3acde22c-d245-480d-b01e-24e38e01806d
