apiVersion: opg.ewbi.nby.one/v1beta1
kind: File
metadata:
  namespace: federation-guest
  labels:
    opg.ewbi.nby.one/federation-context-id: 4d559f1b-f008-58c2-a2f8-0596892a0f7a # get this from Guest Federation's status
    opg.ewbi.nby.one/federation-relation: "guest"
    opg.ewbi.nby.one/id: "file-2dae064c-28cc-456e-8b0a-dd67bab7d8f7"
  name: "file-2dae064c-28cc-456e-8b0a-dd67bab7d8f7"
spec:
  appProviderId: nearbycomputing
  fileName: "nginx:latest"
  fileType: DOCKER
  fileVersion: "latest"
  image:
    instructionSetArchitecture: ISA_X86_64
    os:
      architecture: x86_64
      distribution: UBUNTU
      license: OS_LICENSE_TYPE_FREE
      version: OS_VERSION_UBUNTU_2204_LTS
  repoLocation:
    password: repoPass
    token: repoAccessToken
    type: public
    url: "docker.io"
    username: repoUser